package ChatApp;


/**
* ChatApp/ChatOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Friday, March 6, 2015 3:45:02 PM CET
*/

public interface ChatOperations 
{
  String say (ChatApp.ChatCallback objref, String message);
} // interface ChatOperations
