package ChatApp;


/**
* ChatApp/ChatCallback.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Chat.idl
* Friday, March 6, 2015 3:45:02 PM CET
*/

public interface ChatCallback extends ChatCallbackOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ChatCallback
